baseURL = 'https://transmissionhub.github.io/'
languageCode = 'en-us'
title = 'Transmission Hub'
theme = "hinode"

[params]
  author = "Jonathan"
  description = "A blog about how to use advanced features of Transmission Hub"

  [[params.faq]]
    icon = "telegram"
    name = "Telegram"
    url = "https://t.me/+-IWqdRMKbEJmZjUx"
