[[main]]
  name = "关于"
  pageRef = "/about/"
  weight = 10

[[main]]
  name = "文章"
  pageRef = "/blog/"
  weight = 20

[[main]]
  name = "标签"
  pageRef = "/tags/"
  weight = 40

[[social]]
  name = "App Store"
  pre = "<i class=\"fab fa-app-store-ios fa-2x\"></i>"
  url = "https://apps.apple.com/app/id6448612045"
  weight = 20

[[social]]
  name = "Telegram"
  pre = "<i class=\"fab fa-telegram fa-2x\"></i>"
  url = "https://t.me/+-IWqdRMKbEJmZjUx"
  weight = 20

[[social]]
  name = "Wechat Group"
  pre = "<i class=\"fab fa-weixin fa-2x\"></i>"
  url = "https://cdn.cocac.cc/qrcode.png"
  weight = 20

[[social]]
  name = "Discord"
  pre = "<i class=\"fab fa-discord fa-2x\"></i>"
  url = "https://discord.gg/8C9aucXFmM"
  weight = 20

# toml-docs-start sample-navigation
[[sample]]
  name = "Blog"
  pageRef = "/blog/"
  weight = 10

[[sample]]
  name = "Projects"
  pageRef = "/projects/"
  weight = 20

[[sample]]
  name = "Sample project"
  pageRef = "/projects/sample-project/"
  parent = "Projects"
  weight = 1

[[sample]]
  name = "Another project"
  pageRef = "/projects/another-project/"
  parent = "Projects"
  weight = 2
# toml-docs-end sample-navigation
